--Titan Showdown
local s,id=GetID()
function s.initial_effect(c)
	--Activate
	aux.AddSkillProcedure(c,1,false)
	local e1=Effect.CreateEffect(c)
	e1:SetProperty(EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_CANNOT_DISABLE)
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e1:SetCode(EVENT_STARTUP)
	e1:SetCountLimit(1)
	e1:SetRange(0x5f)
	e1:SetLabel(0)
	e1:SetOperation(s.flipop)
	c:RegisterEffect(e1)
end
function s.flipop(e,tp,eg,ep,ev,re,r,rp)
	Duel.Hint(HINT_SKILL_FLIP,tp,id|(1<<32))
	Duel.Hint(HINT_CARD,tp,id)
	--Double damage
	local e1=Effect.CreateEffect(e:GetHandler())
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_CHANGE_BATTLE_DAMAGE)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetTargetRange(1,0)
	e1:SetCondition(s.damcon1)
	e1:SetValue(DOUBLE_DAMAGE)
	Duel.RegisterEffect(e1,tp)
	local e2=e1:Clone()
	e2:SetTargetRange(0,1)
	e2:SetCondition(s.damcon2)
	Duel.RegisterEffect(e2,tp)
end
function s.damcon1(e)
	local tp=e:GetHandlerPlayer()
	local a,d=Duel.GetAttacker(),Duel.GetAttackTarget()
	return a:GetControler()==1-tp and d and (Duel.GetLP(tp)>=(Duel.GetLP(1-tp)*2))
end
function s.filter(c)
	return c:IsFaceup() and c:IsRace(RACE_DINOSAUR)
end
function s.damcon2(e)
	local tp=e:GetHandlerPlayer()
	local a,d=Duel.GetAttacker(),Duel.GetAttackTarget()
	return a:GetControler()==tp and d and (Duel.GetLP(1-tp)>=(Duel.GetLP(tp)*2))
	and Duel.IsExistingMatchingCard(s.filter,tp,LOCATION_MZONE,0,1,nil)
end
